/**
 * @manifesto-ai/sdk
 *
 * Activation-first SDK package surface.
 *
 * @see sdk-SPEC.md
 * @see ADR-017
 * @packageDocumentation
 */

export type { SdkManifest } from "./manifest.js";

export { createManifesto } from "./create-manifesto.js";

export type {
  ActivatedInstance,
  ActionAnnotation,
  ActionArgs,
  ActionHandle,
  ActionInfo,
  ActionInput,
  ActionName,
  ActionParameterInfo,
  ActionSurface,
  Admission,
  AdmissionFailure,
  AdmissionOk,
  CreateIntentArgs,
  CreateManifestoOptions,
  ContextUpdater,
  DomainExternalContext,
  BaseManifestoApp,
  BaseSubmissionResult,
  DispatchReport,
  DispatchExecutionOutcome,
  DispatchProjectedDiff,
  DispatchCanonicalOutcome,
  ActionObjectBindingArgs,
  Blocker,
  BoundAction,
  DispatchBlocker,
  AvailableActionDelta,
  TypedActionMetadata,
  TypedGetActionMetadata,
  TypedGetIntentBlockers,
  TypedIsIntentDispatchable,
  BaseLaws,
  BaseComposableLaws,
  BaseWriteReport,
  CanonicalNamespaces,
  CanonicalSnapshot,
  ComposableManifesto,
  ComputedReadSurface,
  ComputedRef,
  ChangedPath,
  EffectContext,
  EffectHandler,
  ExecutionDiagnostics,
  ExecutionFailureInfo,
  ExecutionOutcome,
  ExecutionView,
  ExternalContext,
  FieldRef,
  GovernedComposableLaws,
  GovernanceLaws,
  GovernanceSettlementResult,
  GovernanceSettlementSurface,
  GovernanceSubmissionResult,
  IntentAdmission,
  IntentAdmissionFailure,
  IntentExplanation,
  InvalidInputInfo,
  JsonValue,
  LineageComposableLaws,
  LineageLaws,
  LineageSubmissionResult,
  LineageWriteReport,
  ManifestoApp,
  ManifestoDecoratedRuntimeByLaws,
  ManifestoDomainShape,
  ManifestoEvent,
  ManifestoEventName,
  ManifestoEventPayload,
  ManifestoEventPayloadMap,
  ManifestoRuntimeByLaws,
  ObserveSurface,
  Selector,
  SimulationDiagnostics,
  SimulateResult,
  ProjectedDiff,
  ProjectedSnapshot,
  ProposalRef,
  PreviewDiagnosticsMode,
  PreviewResult,
  PathSegment,
  CanonicalOutcome,
  ProjectedReadHandle,
  RuntimeMode,
  SchemaGraph,
  SchemaGraphEdge,
  SchemaGraphEdgeRelation,
  SchemaGraphNode,
  SchemaGraphNodeId,
  SchemaGraphNodeKind,
  SchemaGraphNodeRef,
  Snapshot,
  StateReadSurface,
  SubmissionResult,
  SubmitReportMode,
  SubmitResultFor,
  TypedActionRef,
  TypedCreateIntent,
  TypedDomainRefs,
  TypedIntent,
  TypedMEL,
  TypedOn,
  TypedSubscribe,
  Unsubscribe,
  WorldRecord,
} from "./types.js";

export {
  AlreadyActivatedError,
  CompileError,
  DisposedError,
  ManifestoError,
  ReservedEffectError,
  SubmissionFailedError,
} from "./errors.js";

export type { CompileDiagnostic } from "./errors.js";

export type {
  DomainSchema,
  Intent,
  Patch,
  Snapshot as CoreSnapshot,
} from "@manifesto-ai/core";

export { createSnapshot } from "@manifesto-ai/core";
