/**
 * Provenance Types Tests
 *
 * Tests for provenance factory functions in src/types/provenance.ts
 */

import { describe, it, expect } from 'vitest';
import {
  codeOrigin,
  textOrigin,
  generatedOrigin,
  patchOrigin,
  llmOrigin,
  createProvenance,
  createEvidence,
  type CodeSpan,
  type TextSpan,
  type OriginLocation,
  type Provenance,
  type Evidence,
  type EvidenceKind,
} from '../../src/types/provenance.js';

// ============================================================================
// codeOrigin
// ============================================================================

describe('codeOrigin', () => {
  it('should create code origin with span', () => {
    const span: CodeSpan = {
      file: 'src/main.ts',
      startLine: 10,
      startCol: 0,
      endLine: 15,
      endCol: 20,
    };

    const origin = codeOrigin(span);

    expect(origin.kind).toBe('code');
    expect((origin as any).span).toEqual(span);
  });

  it('should work without optional file', () => {
    const span: CodeSpan = {
      startLine: 1,
      startCol: 0,
      endLine: 1,
      endCol: 10,
    };

    const origin = codeOrigin(span);

    expect(origin.kind).toBe('code');
    expect((origin as any).span.file).toBeUndefined();
  });

  it('should preserve all span properties', () => {
    const span: CodeSpan = {
      file: 'test.js',
      startLine: 100,
      startCol: 50,
      endLine: 200,
      endCol: 100,
    };

    const origin = codeOrigin(span) as { kind: 'code'; span: CodeSpan };

    expect(origin.span.file).toBe('test.js');
    expect(origin.span.startLine).toBe(100);
    expect(origin.span.startCol).toBe(50);
    expect(origin.span.endLine).toBe(200);
    expect(origin.span.endCol).toBe(100);
  });
});

// ============================================================================
// textOrigin
// ============================================================================

describe('textOrigin', () => {
  it('should create text origin with span', () => {
    const span: TextSpan = {
      docId: 'doc_123',
      startOffset: 0,
      endOffset: 100,
    };

    const origin = textOrigin(span);

    expect(origin.kind).toBe('text');
    expect((origin as any).span).toEqual(span);
  });

  it('should work without optional docId', () => {
    const span: TextSpan = {
      startOffset: 50,
      endOffset: 150,
    };

    const origin = textOrigin(span);

    expect(origin.kind).toBe('text');
    expect((origin as any).span.docId).toBeUndefined();
  });
});

// ============================================================================
// generatedOrigin
// ============================================================================

describe('generatedOrigin', () => {
  it('should create generated origin with note', () => {
    const origin = generatedOrigin('Auto-generated by compiler');

    expect(origin.kind).toBe('generated');
    expect((origin as any).note).toBe('Auto-generated by compiler');
  });

  it('should handle empty note', () => {
    const origin = generatedOrigin('');

    expect(origin.kind).toBe('generated');
    expect((origin as any).note).toBe('');
  });

  it('should handle unicode in note', () => {
    const origin = generatedOrigin('자동 생성됨');

    expect((origin as any).note).toBe('자동 생성됨');
  });
});

// ============================================================================
// patchOrigin
// ============================================================================

describe('patchOrigin', () => {
  it('should create patch origin with ID', () => {
    const origin = patchOrigin('patch_12345_abc');

    expect(origin.kind).toBe('patch');
    expect((origin as any).patchId).toBe('patch_12345_abc');
  });

  it('should handle various patch ID formats', () => {
    const ids = ['patch_1', 'p-123', 'custom_id'];

    for (const id of ids) {
      const origin = patchOrigin(id);
      expect((origin as any).patchId).toBe(id);
    }
  });
});

// ============================================================================
// llmOrigin
// ============================================================================

describe('llmOrigin', () => {
  it('should create LLM origin with model', () => {
    const origin = llmOrigin('gpt-4');

    expect(origin.kind).toBe('llm');
    expect((origin as any).model).toBe('gpt-4');
    expect((origin as any).promptHash).toBeUndefined();
  });

  it('should create LLM origin with model and prompt hash', () => {
    const origin = llmOrigin('claude-3', 'abc123');

    expect(origin.kind).toBe('llm');
    expect((origin as any).model).toBe('claude-3');
    expect((origin as any).promptHash).toBe('abc123');
  });

  it('should handle various model names', () => {
    const models = ['gpt-4', 'claude-3-opus', 'llama-2-70b', 'custom-fine-tuned'];

    for (const model of models) {
      const origin = llmOrigin(model);
      expect((origin as any).model).toBe(model);
    }
  });
});

// ============================================================================
// createProvenance
// ============================================================================

describe('createProvenance', () => {
  it('should create provenance with required fields', () => {
    const location = generatedOrigin('test');
    const provenance = createProvenance('artifact_1', location);

    expect(provenance.artifactId).toBe('artifact_1');
    expect(provenance.location).toEqual(location);
    expect(provenance.originHash).toBeUndefined();
    expect(typeof provenance.createdAt).toBe('number');
  });

  it('should include origin hash when provided', () => {
    const location = codeOrigin({ startLine: 1, startCol: 0, endLine: 1, endCol: 10 });
    const provenance = createProvenance('artifact_1', location, 'hash_abc123');

    expect(provenance.originHash).toBe('hash_abc123');
  });

  it('should have current timestamp', () => {
    const before = Date.now();
    const provenance = createProvenance('a', generatedOrigin(''));
    const after = Date.now();

    expect(provenance.createdAt).toBeGreaterThanOrEqual(before);
    expect(provenance.createdAt).toBeLessThanOrEqual(after);
  });

  it('should work with all location types', () => {
    const locations: OriginLocation[] = [
      codeOrigin({ startLine: 1, startCol: 0, endLine: 1, endCol: 10 }),
      textOrigin({ startOffset: 0, endOffset: 100 }),
      generatedOrigin('test'),
      patchOrigin('patch_1'),
      llmOrigin('model-1', 'hash'),
    ];

    for (const location of locations) {
      const provenance = createProvenance('artifact', location);
      expect(provenance.location).toEqual(location);
    }
  });
});

// ============================================================================
// createEvidence
// ============================================================================

describe('createEvidence', () => {
  it('should create evidence with required fields', () => {
    const evidence = createEvidence('quote', 'source.ts:10');

    expect(evidence.kind).toBe('quote');
    expect(evidence.ref).toBe('source.ts:10');
    expect(evidence.excerpt).toBeUndefined();
    expect(evidence.confidence).toBeUndefined();
  });

  it('should create evidence with excerpt', () => {
    const evidence = createEvidence('quote', 'doc.md:5', 'User authentication flow');

    expect(evidence.excerpt).toBe('User authentication flow');
  });

  it('should create evidence with confidence', () => {
    const evidence = createEvidence('llm_reasoning', 'chain-of-thought', undefined, 0.85);

    expect(evidence.kind).toBe('llm_reasoning');
    expect(evidence.confidence).toBe(0.85);
  });

  it('should create evidence with all optional fields', () => {
    const evidence = createEvidence(
      'ast_node',
      'FunctionDeclaration',
      'function doSomething()',
      0.95
    );

    expect(evidence.kind).toBe('ast_node');
    expect(evidence.ref).toBe('FunctionDeclaration');
    expect(evidence.excerpt).toBe('function doSomething()');
    expect(evidence.confidence).toBe(0.95);
  });

  it('should handle all evidence kinds', () => {
    const kinds: EvidenceKind[] = [
      'quote',
      'ast_node',
      'rule',
      'link',
      'fragment_ref',
      'llm_reasoning',
    ];

    for (const kind of kinds) {
      const evidence = createEvidence(kind, 'ref');
      expect(evidence.kind).toBe(kind);
    }
  });
});

// ============================================================================
// Edge Cases
// ============================================================================

describe('Edge Cases', () => {
  it('should handle zero line/column numbers', () => {
    const span: CodeSpan = {
      startLine: 0,
      startCol: 0,
      endLine: 0,
      endCol: 0,
    };

    const origin = codeOrigin(span);
    expect((origin as any).span.startLine).toBe(0);
  });

  it('should handle large offset values', () => {
    const span: TextSpan = {
      startOffset: Number.MAX_SAFE_INTEGER - 1,
      endOffset: Number.MAX_SAFE_INTEGER,
    };

    const origin = textOrigin(span);
    expect((origin as any).span.startOffset).toBe(Number.MAX_SAFE_INTEGER - 1);
  });

  it('should handle unicode in references', () => {
    const evidence = createEvidence('quote', '소스코드.ts:10', '한글 주석');

    expect(evidence.ref).toBe('소스코드.ts:10');
    expect(evidence.excerpt).toBe('한글 주석');
  });

  it('should handle empty strings', () => {
    const origin = generatedOrigin('');
    expect((origin as any).note).toBe('');

    const evidence = createEvidence('rule', '', '');
    expect(evidence.ref).toBe('');
    expect(evidence.excerpt).toBe('');
  });

  it('should handle special characters in artifact ID', () => {
    const provenance = createProvenance(
      'artifact-with_special.chars:123',
      generatedOrigin('test')
    );

    expect(provenance.artifactId).toBe('artifact-with_special.chars:123');
  });

  it('should handle confidence edge values', () => {
    const zeroConf = createEvidence('llm_reasoning', 'ref', undefined, 0);
    expect(zeroConf.confidence).toBe(0);

    const oneConf = createEvidence('llm_reasoning', 'ref', undefined, 1);
    expect(oneConf.confidence).toBe(1);
  });
});
