name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: "@manifesto-ai/core"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Create a domain with...
        2. Call compute with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context about the problem (screenshots, logs, etc.)

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Node.js
        - Browser
        - Both
    validations:
      required: true
