export type {
  Patch,
  Snapshot,
  ArtifactRef,
  BranchId,
  BranchInfo,
  BranchSwitchResult,
  CurrentErrorSignature,
  LineageService,
  LineageStore,
  PersistedBranchEntry,
  PersistedBranchState,
  PersistedPatchDeltaV2,
  PreparedBranchBootstrap,
  PreparedBranchChange,
  PreparedBranchMutation,
  PreparedGenesisCommit,
  PreparedLineageCommit,
  PreparedLineageRecords,
  PreparedNextCommit,
  ProvenanceRef,
  SchemaHash,
  SealAttempt,
  SealGenesisInput,
  SealNextInput,
  SnapshotHashInput,
  TerminalStatus,
  World,
  WorldEdge,
  WorldHead,
  WorldId,
  WorldLineage,
} from "@manifesto-ai/lineage";

export {
  DefaultLineageService,
  buildWorldLineage,
  computePendingDigest,
  computeSnapshotHash,
  computeWorldId,
  createLineageService,
  createSnapshotHashInput,
  deriveTerminalStatus,
  getHeadsFromStore,
  isPlatformNamespace,
  normalizeContext,
  restoreSnapshot,
  selectLatestHead,
  stripPlatformNamespaces,
  toBranchInfo,
  toCurrentErrorSignature,
  toWorldHead,
} from "@manifesto-ai/lineage";

export type {
  ActorAuthorityBinding,
  ActorId,
  ActorKind,
  ActorRef,
  AuthorityHandler,
  AuthorityId,
  AuthorityKind,
  AuthorityPolicy,
  AuthorityRef,
  AuthorityResponse,
  CreateProposalInput,
  CreateIntentInstanceOptions,
  CustomConditionEvaluator,
  DecisionId,
  DecisionRecord,
  ErrorInfo,
  ExecutionCompletedEvent,
  ExecutionFailedEvent,
  ExecutionKey,
  ExecutionKeyContext,
  ExecutionKeyPolicy,
  FinalDecision,
  GovernanceEvent,
  GovernanceEventSink,
  GovernanceEventType,
  GovernanceService,
  GovernanceStore,
  HITLDecisionCallback,
  HITLNotificationCallback,
  HITLPendingState,
  IntentBody,
  IntentInstance,
  IntentOrigin,
  Intent,
  IntentScope,
  PolicyCondition,
  PolicyRule,
  PrepareAuthorityResultOptions,
  PreparedAuthorityResult,
  PreparedGovernanceCommit,
  Proposal,
  ProposalDecidedEvent,
  ProposalEvaluatingEvent,
  ProposalId,
  ProposalStatus,
  ProposalSubmittedEvent,
  ProposalSupersededEvent,
  QuorumRule,
  SourceKind,
  SourceRef,
  SupersedeReason,
  Vote,
  WaitingFor,
  WorldCreatedEvent,
  WorldForkedEvent,
} from "@manifesto-ai/governance";

export {
  AuthorityEvaluator,
  AutoApproveHandler,
  DefaultGovernanceService,
  HITLHandler,
  PolicyRulesHandler,
  TribunalHandler,
  createAuthorityEvaluator,
  createAutoApproveHandler,
  createDecisionId,
  createExecutionKey,
  createIntentInstance,
  createIntentInstanceSync,
  createGovernanceEventDispatcher,
  createGovernanceService,
  createNoopGovernanceEventSink,
  createPolicyRulesHandler,
  createProposalId,
  createTribunalHandler,
  computeIntentKey,
  defaultExecutionKeyPolicy,
  getValidTransitions,
  isExecutionStageStatus,
  isIngressStatus,
  isTerminalStatus,
  isValidTransition,
  toHostIntent,
  transitionCreatesDecisionRecord,
  DECISION_TRANSITION_TARGETS,
  EXECUTION_STAGE_STATUSES,
  INGRESS_STATUSES,
  TERMINAL_STATUSES,
} from "@manifesto-ai/governance";

export type {
  CoordinatorSealGenesisParams,
  CoordinatorSealNextParams,
  ExecuteApprovedProposalInput,
  GovernedWorldStore,
  GovernanceEventDispatcher,
  RecoveredWorldRuntimeCompletion,
  ResumeExecutingProposalInput,
  SealResult,
  SealedWorldRuntimeCompletion,
  WorldExecutionOptions,
  WorldRuntimeCompletion,
  WorldExecutionResult,
  WorldExecutor,
  WorldStoreTransaction,
  WorldConfig,
  WorldCoordinator,
  WorldInstance,
  WorldRuntime,
} from "./types.js";

export { createWorld } from "./create-world.js";
export {
  IndexedDbGovernedWorldStore,
  InMemoryGovernedWorldStore,
  SqliteGovernedWorldStore,
  createIndexedDbWorldStore,
  createInMemoryWorldStore,
  createSqliteWorldStore,
} from "./store.js";
export type {
  IndexedDbWorldStoreOptions,
  SqliteWorldStoreOptions,
} from "./store.js";
export {
  DefaultWorldCoordinator,
  createWorldCoordinator,
} from "./coordinator.js";
