export interface HeaderOptions {
  readonly sourceId?: string;
  readonly schemaHash: string;
  readonly stamp?: boolean;
}

/**
 * Generate the @generated file header (DET-2, DET-3, DET-4).
 *
 * Default mode: no timestamp (deterministic).
 * With stamp=true: appends ISO 8601 timestamp line.
 */
export function generateHeader(options: HeaderOptions): string {
  const source = options.sourceId ?? "unknown";
  const lines = [
    "// @generated by @manifesto-ai/codegen \u2014 DO NOT EDIT",
    `// Source: ${source} | Schema hash: ${options.schemaHash}`,
  ];

  if (options.stamp) {
    lines.push(`// Generated at: ${new Date().toISOString()}`);
  }

  return lines.join("\n") + "\n";
}
