/**
 * Domain Converter - Convert DomainDraft to ManifestoDomain
 *
 * Required for Core validateDomain integration.
 * Maintains determinism (Principle E).
 *
 * This module converts the compiler's DomainDraft (intermediate representation)
 * into a fully-formed ManifestoDomain that can be validated by Core's validateDomain.
 */

import { z, type ZodObject, type ZodRawShape, type ZodTypeAny } from 'zod';
import type {
  ManifestoDomain,
  SemanticPath,
  PathDefinitions,
  AsyncDefinition,
} from '@manifesto-ai/core';
import type { DomainDraft } from '../types/session.js';
import type { ExtendedLinkResult } from '../linker/index.js';

// ============================================================================
// Types
// ============================================================================

/**
 * Options for domain conversion
 */
export interface ConvertOptions {
  /** Default domain ID if not provided in draft */
  defaultId?: string;

  /** Default domain name if not provided in draft */
  defaultName?: string;

  /** Default domain description if not provided in draft */
  defaultDescription?: string;

  /** Pre-built Zod schemas (from DomainBuildResult) */
  zodSchemas?: {
    data: ZodObject<ZodRawShape>;
    state: ZodObject<ZodRawShape>;
  };
}

// Re-export for convenience (already exported from linker)
export type { ExtendedLinkResult };

// ============================================================================
// Main Conversion Function
// ============================================================================

/**
 * Convert DomainDraft to ManifestoDomain
 *
 * This conversion is required because:
 * - DomainDraft has optional id/name/description
 * - DomainDraft stores schemas as Record<string, unknown>
 * - ManifestoDomain requires Zod schemas and has required fields
 *
 * @param draft - DomainDraft from the linker
 * @param options - Conversion options
 * @returns ManifestoDomain suitable for Core validation
 */
export function convertDomainDraftToManifesto(
  draft: DomainDraft,
  options: ConvertOptions = {}
): ManifestoDomain<unknown, unknown> {
  const {
    defaultId = 'compiler-generated-domain',
    defaultName = 'Generated Domain',
    defaultDescription = 'Domain generated by @manifesto-ai/compiler',
    zodSchemas,
  } = options;

  // Build Zod schemas
  const dataSchema = zodSchemas?.data ?? buildZodSchemaFromRecord(draft.dataSchema);
  const stateSchema = zodSchemas?.state ?? buildZodSchemaFromRecord(draft.stateSchema);

  // Build path definitions
  const paths: PathDefinitions<unknown, unknown> = {
    sources: draft.sources,
    derived: draft.derived,
    async: {}, // DomainDraft doesn't include async definitions
  };

  // Build initial state
  const initialState = draft.initialState ?? buildInitialState(stateSchema);

  return {
    id: draft.id ?? defaultId,
    name: draft.name ?? defaultName,
    description: draft.description ?? defaultDescription,
    paths,
    actions: draft.actions,
    dataSchema,
    stateSchema,
    initialState,
  };
}

/**
 * Convert DomainDraft to ManifestoDomain using LinkResult context
 *
 * This is the preferred method when you have access to the full LinkResult,
 * as it can use pre-built Zod schemas from DomainBuildResult.
 *
 * @param draft - DomainDraft from the linker
 * @param linkResult - Extended LinkResult with optional DomainBuildResult
 * @param options - Additional conversion options
 * @returns ManifestoDomain suitable for Core validation
 */
export function convertFromLinkResult(
  draft: DomainDraft,
  linkResult?: ExtendedLinkResult,
  options: ConvertOptions = {}
): ManifestoDomain<unknown, unknown> {
  // Use zodSchemas from DomainBuildResult if available
  const zodSchemas = linkResult?.domainBuildResult?.zodSchemas;

  return convertDomainDraftToManifesto(draft, {
    ...options,
    zodSchemas: zodSchemas ?? options.zodSchemas,
  });
}

// ============================================================================
// Schema Building Utilities
// ============================================================================

/**
 * Build a Zod schema from a Record<string, unknown> schema representation
 *
 * The record contains field names mapped to type descriptions (e.g., "string", "number").
 * This reverses the zodSchemaToPlainObject transformation from domain-builder.ts.
 *
 * @param schemaRecord - Schema representation from DomainDraft
 * @returns Zod object schema
 */
export function buildZodSchemaFromRecord(
  schemaRecord: Record<string, unknown>
): ZodObject<ZodRawShape> {
  const shape: ZodRawShape = {};

  for (const [key, typeDesc] of Object.entries(schemaRecord)) {
    shape[key] = typeDescriptionToZod(typeDesc);
  }

  return z.object(shape);
}

/**
 * Convert a type description back to a Zod type
 *
 * Handles the type strings produced by zodTypeDescription in domain-builder.ts.
 *
 * @param typeDesc - Type description (string or complex)
 * @returns Zod type
 */
function typeDescriptionToZod(typeDesc: unknown): ZodTypeAny {
  if (typeof typeDesc !== 'string') {
    // Complex type - treat as unknown
    return z.unknown();
  }

  // Handle optional types (e.g., "string?")
  if (typeDesc.endsWith('?')) {
    const innerType = typeDesc.slice(0, -1);
    return typeDescriptionToZod(innerType).optional();
  }

  // Handle nullable types (e.g., "string | null")
  if (typeDesc.includes(' | null')) {
    const innerType = typeDesc.replace(' | null', '');
    return typeDescriptionToZod(innerType).nullable();
  }

  // Handle base types
  switch (typeDesc.toLowerCase()) {
    case 'string':
      return z.string();
    case 'number':
      return z.number();
    case 'boolean':
      return z.boolean();
    case 'array':
      return z.array(z.unknown());
    case 'object':
      return z.record(z.unknown());
    case 'null':
      return z.null();
    case 'unknown':
    default:
      return z.unknown();
  }
}

/**
 * Build initial state from a state schema
 *
 * Creates default values for each field based on its type.
 *
 * @param stateSchema - Zod state schema
 * @returns Initial state object
 */
function buildInitialState(stateSchema: ZodObject<ZodRawShape>): Record<string, unknown> {
  const state: Record<string, unknown> = {};
  const shape = stateSchema.shape;

  for (const [key, zodType] of Object.entries(shape)) {
    state[key] = getDefaultForZodType(zodType as ZodTypeAny);
  }

  return state;
}

/**
 * Get default value for a Zod type
 *
 * @param zodType - Zod type
 * @returns Default value for the type
 */
function getDefaultForZodType(zodType: ZodTypeAny): unknown {
  const typeName = zodType._def?.typeName;

  switch (typeName) {
    case 'ZodString':
      return '';
    case 'ZodNumber':
      return 0;
    case 'ZodBoolean':
      return false;
    case 'ZodArray':
      return [];
    case 'ZodObject':
    case 'ZodRecord':
      return {};
    case 'ZodNull':
      return null;
    case 'ZodOptional':
      return undefined;
    case 'ZodNullable':
      return null;
    case 'ZodDefault':
      return (zodType as any)._def.defaultValue();
    default:
      return undefined;
  }
}

// ============================================================================
// Validation Helpers
// ============================================================================

/**
 * Check if a DomainDraft is complete enough for conversion
 *
 * @param draft - DomainDraft to check
 * @returns Object with isValid flag and any issues
 */
export function isDraftConvertible(draft: DomainDraft): {
  isValid: boolean;
  issues: string[];
} {
  const issues: string[] = [];

  // Check for minimum required fields
  if (!draft.sources || Object.keys(draft.sources).length === 0) {
    // Sources can be empty, but we note it
  }

  if (!draft.derived || Object.keys(draft.derived).length === 0) {
    // Derived can be empty, but we note it
  }

  // Check for schema presence
  if (!draft.dataSchema || Object.keys(draft.dataSchema).length === 0) {
    issues.push('Empty data schema');
  }

  return {
    isValid: issues.length === 0,
    issues,
  };
}

export default {
  convertDomainDraftToManifesto,
  convertFromLinkResult,
  buildZodSchemaFromRecord,
  isDraftConvertible,
};
