// @generated by @manifesto-ai/codegen — DO NOT EDIT
// Source: src/domain/todo.mel | Schema hash: 8e916dc40d9f36386333d3b76d8942f82d8d8c65a94ec2f2a7ff5dfbe8f9f2fb
import type {
  ActionArgs,
  ActionHandle,
  ActionInput,
  ManifestoApp,
  RuntimeMode,
} from "@manifesto-ai/sdk";

export interface Todo {
  completed: boolean;
  id: string;
  title: string;
}

export interface TodoDomain {
  readonly state: {
    filterMode: "all" | "active" | "completed"
    todos: Todo[]
  }
  readonly computed: {
    activeCount: number
    completedCount: number
    hasCompleted: boolean
    todoCount: number
  }
  readonly actions: {
    addTodo: (title: string) => void
    clearCompleted: () => void
    removeTodo: (id: string) => void
    setFilter: (newFilter: "all" | "active" | "completed") => void
    toggleTodo: (id: string) => void
  }
}

export type TodoActionInput<Name extends keyof TodoDomain["actions"] & string> =
  ActionInput<TodoDomain, Name>;

export type TodoActionArgs<Name extends keyof TodoDomain["actions"] & string> =
  ActionArgs<TodoDomain, Name>;

export type TodoActions<TMode extends RuntimeMode> = {
  readonly [Name in keyof TodoDomain["actions"] & string]:
    ActionHandle<TodoDomain, Name, TMode>;
};

export type TodoActionAccessor<TMode extends RuntimeMode> =
  ManifestoApp<TodoDomain, TMode>["action"];

export type TodoApp<TMode extends RuntimeMode> =
  ManifestoApp<TodoDomain, TMode>;
