// Legacy validation functions (for backward compatibility)
export {
  validateSchema,
  validateEntitySchema,
  validateViewSchema,
  validateActionSchema,
  type ValidationError,
} from './schema'

// New Zod schemas (Single Source of Truth)
// Export all schemas with unique names
export {
  // Common
  schemaVersionSchema,
  schemaMetadataSchema,
  // Expression
  operatorSchema,
  literalSchema,
  contextReferenceSchema,
  expressionSchema,
  // Entity
  dataTypeSchema,
  constraintTypeSchema,
  constraintSchema,
  enumValueSchema,
  cascadeTypeSchema,
  referenceConfigSchema,
  entityFieldSchema,
  relationTypeSchema,
  relationSchema,
  indexConfigSchema,
  entitySchemaValidator,
  // View
  layoutTypeSchema,
  layoutConfigSchema,
  componentTypeSchema,
  styleConfigSchema,
  dataSourceTypeSchema,
  apiDataSourceSchema,
  dataSourceSchema,
  setValueActionSchema,
  setOptionsActionSchema,
  updatePropActionSchema,
  validateActionSchema as validateActionZodSchema,
  navigateActionSchema,
  emitActionSchema,
  reactionActionSchema,
  reactionTriggerSchema,
  reactionSchema,
  viewFieldSchema,
  viewSectionSchema,
  confirmConfigSchema,
  actionReferenceTypeSchema,
  actionReferenceSchema,
  buttonVariantSchema,
  viewActionSchema,
  viewHeaderSchema,
  viewFooterSchema,
  formViewSchemaValidator,
  // List
  columnTypeSchema,
  numberFormatSchema,
  badgeVariantSchema,
  badgeConfigSchema,
  columnFormatSchema,
  columnSummaryTypeSchema,
  columnSummarySchema,
  rowActionSchema,
  bulkActionSchema,
  columnAlignSchema,
  listColumnSchema,
  paginationConfigSchema,
  sortDirectionSchema,
  sortingConfigSchema,
  filterFieldTypeSchema,
  filterFieldSchema,
  filterConfigSchema,
  selectionModeSchema,
  selectionConfigSchema,
  listDataSourceSchema,
  emptyStateConfigSchema,
  listViewSchemaValidator,
  // Action
  actionTriggerTypeSchema,
  actionTriggerSchema,
  transformOperationSchema,
  transformStepSchema,
  transformPipelineSchema,
  adapterTypeSchema,
  adapterConfigSchema,
  httpMethodSchema,
  apiCallStepSchema,
  setStateStepSchema,
  navigationStepSchema,
  actionStepSchema,
  actionSchemaValidator,
  // Unified
  viewSchemaValidator,
  unifiedSchemaValidator,
} from './schemas'
