/**
 * Codebook Types - Semantic Path Aliasing System
 *
 * A Codebook is a collection of alias -> canonical path mappings.
 * Aliases allow compressing similar Intent expressions into stable Semantic Paths.
 * This implements "Semantic Huffman Coding" - frequently occurring patterns
 * get shorter, more stable paths.
 *
 * CRITICAL INVARIANTS:
 * - NO AUTO-MERGE: All alias operations are SUGGESTIONS only
 * - NO SILENT RESOLUTION: Aliases must be explicitly applied via PatchOps
 * - Principle E: All operations are deterministic (sorted, reproducible)
 */

import type { SemanticPath } from '@manifesto-ai/core';
import type { FragmentId } from './fragment.js';
import type { Provenance, Evidence } from './provenance.js';

// ============================================================================
// ID Types
// ============================================================================

/** Unique identifier for a codebook */
export type CodebookId = string;

/** Unique identifier for an alias entry */
export type AliasId = string;

// ============================================================================
// Alias Status
// ============================================================================

/**
 * Alias status - whether this alias is a suggestion or has been applied
 */
export type AliasStatus =
  | 'suggested' // Generated by the system, not yet applied
  | 'applied' // User/agent explicitly applied this alias
  | 'rejected'; // User/agent explicitly rejected this alias

// ============================================================================
// Core Types
// ============================================================================

/**
 * Alias entry - maps an alias path to a canonical path
 *
 * This is the core data structure for path convergence without forced resolution.
 */
export interface AliasEntry {
  /** Unique alias identifier */
  id: AliasId;

  /** The alias path (source - the path being aliased) */
  aliasPath: SemanticPath;

  /** The canonical path (target - the stable path to use) */
  canonicalPath: SemanticPath;

  /** Status of this alias */
  status: AliasStatus;

  /** Confidence score (0-1) for the alias suggestion */
  confidence: number;

  /** Why this alias was suggested */
  rationale: string;

  /** Provenance: who/what created this alias */
  origin: Provenance;

  /** Evidence supporting this alias */
  evidence?: Evidence[];

  /** Fragment IDs affected by this alias */
  affectedFragments: FragmentId[];

  /** Timestamp when this alias was created */
  createdAt: number;

  /** Timestamp when this alias was applied/rejected (if applicable) */
  resolvedAt?: number;
}

/**
 * Codebook - collection of alias entries
 *
 * The Codebook enables path convergence (Semantic Huffman Coding) while
 * maintaining the compiler's deterministic invariants.
 */
export interface Codebook {
  /** Unique codebook identifier */
  id: CodebookId;

  /** Human-readable name */
  name?: string;

  /** Description of this codebook's purpose */
  description?: string;

  /** All alias entries in this codebook */
  entries: AliasEntry[];

  /** Version for incremental updates */
  version: string;

  /** Timestamp when this codebook was created */
  createdAt: number;

  /** Timestamp when this codebook was last updated */
  updatedAt: number;
}

// ============================================================================
// Suggestion Types
// ============================================================================

/**
 * Alias suggestion - generated by the system for user review
 *
 * This is what the hint-generator produces. It becomes an AliasEntry
 * when applied via a PatchOp.
 *
 * CRITICAL: Suggestions are NEVER auto-applied.
 */
export interface AliasSuggestion {
  /** The alias path (source) */
  aliasPath: SemanticPath;

  /** The canonical path (target) */
  canonicalPath: SemanticPath;

  /** Confidence score (0-1) */
  confidence: number;

  /** Why this alias is suggested */
  rationale: string;

  /** Fragment IDs that would be affected */
  affectedFragments: FragmentId[];

  /** Similarity score between the paths (0-1) */
  similarityScore?: number;

  /** Type of similarity detected */
  similarityType?: SimilarityType;
}

/**
 * Similarity types for alias suggestions
 */
export type SimilarityType =
  | 'semantic' // Path names are semantically similar
  | 'structural' // Path structure is similar
  | 'expression' // Expression contents are similar
  | 'usage'; // Usage patterns are similar

// ============================================================================
// Analysis Results
// ============================================================================

/**
 * Codebook analysis result - output of analyzing fragments for potential aliases
 */
export interface CodebookAnalysisResult {
  /** Suggested aliases (NOT auto-applied) */
  suggestions: AliasSuggestion[];

  /** Paths that have high frequency (candidates for canonical status) */
  frequentPaths: Array<{ path: SemanticPath; count: number }>;

  /** Path clusters (groups of similar paths) */
  clusters: Array<{
    paths: SemanticPath[];
    suggestedCanonical: SemanticPath;
    confidence: number;
  }>;

  /** Statistics about the analysis */
  stats: CodebookAnalysisStats;
}

/**
 * Statistics from codebook analysis
 */
export interface CodebookAnalysisStats {
  /** Total number of paths analyzed */
  totalPaths: number;

  /** Number of unique paths */
  uniquePaths: number;

  /** Number of potential aliases found */
  potentialAliases: number;

  /** Estimated compression ratio (0-1, how much path space could be compressed) */
  estimatedCompression: number;
}

// ============================================================================
// Configuration Types
// ============================================================================

/**
 * Configuration for alias hint generation
 */
export interface AliasHintConfig {
  /** Minimum similarity score for name-based suggestions (0-1) */
  nameSimilarityThreshold?: number;

  /** Minimum similarity score for expression-based suggestions (0-1) */
  expressionSimilarityThreshold?: number;

  /** Minimum confidence to include a suggestion */
  minConfidence?: number;

  /** Maximum suggestions to return */
  maxSuggestions?: number;

  /** Whether to prefer shorter paths as canonical */
  preferShorterPaths?: boolean;

  /** Whether to prefer more frequently used paths as canonical */
  preferFrequentPaths?: boolean;
}

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Create a unique codebook ID
 */
export function createCodebookId(): CodebookId {
  return `codebook_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
}

/**
 * Create a unique alias ID
 */
export function createAliasId(): AliasId {
  return `alias_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
}

/**
 * Create an empty codebook
 */
export function createCodebook(name?: string, description?: string): Codebook {
  return {
    id: createCodebookId(),
    name,
    description,
    entries: [],
    version: `v_${Date.now()}`,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}

/**
 * Create an alias entry (defaults to suggested state)
 */
export function createAliasEntry(
  aliasPath: SemanticPath,
  canonicalPath: SemanticPath,
  origin: Provenance,
  options: {
    status?: AliasStatus;
    confidence?: number;
    rationale?: string;
    affectedFragments?: FragmentId[];
    evidence?: Evidence[];
  } = {}
): AliasEntry {
  const now = Date.now();
  return {
    id: createAliasId(),
    aliasPath,
    canonicalPath,
    status: options.status ?? 'suggested',
    confidence: options.confidence ?? 0.5,
    rationale: options.rationale ?? 'Auto-generated alias suggestion',
    origin,
    evidence: options.evidence,
    affectedFragments: options.affectedFragments ?? [],
    createdAt: now,
    resolvedAt: options.status === 'applied' || options.status === 'rejected' ? now : undefined,
  };
}

/**
 * Create an alias suggestion
 */
export function createAliasSuggestion(
  aliasPath: SemanticPath,
  canonicalPath: SemanticPath,
  options: {
    confidence?: number;
    rationale?: string;
    affectedFragments?: FragmentId[];
    similarityScore?: number;
    similarityType?: SimilarityType;
  } = {}
): AliasSuggestion {
  return {
    aliasPath,
    canonicalPath,
    confidence: options.confidence ?? 0.5,
    rationale: options.rationale ?? 'Similar paths detected',
    affectedFragments: options.affectedFragments ?? [],
    similarityScore: options.similarityScore,
    similarityType: options.similarityType,
  };
}

// ============================================================================
// Default Configuration
// ============================================================================

/**
 * Default alias hint configuration
 */
export const DEFAULT_ALIAS_HINT_CONFIG: Required<AliasHintConfig> = {
  nameSimilarityThreshold: 0.75,
  expressionSimilarityThreshold: 0.85,
  minConfidence: 0.5,
  maxSuggestions: 50,
  preferShorterPaths: true,
  preferFrequentPaths: true,
};
