/**
 * Core Integration Tests
 *
 * Tests the integration between @manifesto-ai/compiler verifier
 * and @manifesto-ai/core validateDomain.
 *
 * These tests verify:
 * - DomainDraft to ManifestoDomain conversion
 * - Core validateDomain integration
 * - Issue mapping from Core to compiler format
 * - Determinism with Core validation enabled
 */

import { describe, it, expect } from 'vitest';
import {
  verify,
  convertDomainDraftToManifesto,
  buildZodSchemaFromRecord,
  isDraftConvertible,
  type VerifyOptions,
} from '../../src/verifier/index.js';
import { link } from '../../src/linker/index.js';
import type {
  Fragment,
  SchemaFragment,
  SourceFragment,
  DerivedFragment,
  ActionFragment,
} from '../../src/types/fragment.js';
import type { DomainDraft, LinkResult } from '../../src/types/session.js';

// ============================================================================
// Test Helpers
// ============================================================================

function createSchemaFragment(overrides: Partial<SchemaFragment> = {}): SchemaFragment {
  return {
    id: 'schema-1',
    kind: 'SchemaFragment',
    requires: [],
    provides: ['data.count'],
    origin: { artifactId: 'test', location: { kind: 'generated', note: 'test' } },
    evidence: [],
    compilerVersion: '0.1.0',
    namespace: 'data',
    fields: [{ path: 'data.count', type: 'number', semantic: {} }],
    ...overrides,
  };
}

function createSourceFragment(overrides: Partial<SourceFragment> = {}): SourceFragment {
  return {
    id: 'source-1',
    kind: 'SourceFragment',
    requires: [],
    provides: ['data.input'],
    origin: { artifactId: 'test', location: { kind: 'generated', note: 'test' } },
    evidence: [],
    compilerVersion: '0.1.0',
    path: 'data.input',
    type: 'string',
    schema: { type: 'string' },
    semantic: { type: 'string', description: 'User input' },
    ...overrides,
  };
}

function createDerivedFragment(overrides: Partial<DerivedFragment> = {}): DerivedFragment {
  return {
    id: 'derived-1',
    kind: 'DerivedFragment',
    requires: ['data.count'],
    provides: ['derived.doubled'],
    origin: { artifactId: 'test', location: { kind: 'generated', note: 'test' } },
    evidence: [],
    compilerVersion: '0.1.0',
    path: 'derived.doubled',
    expr: ['*', ['get', 'data.count'], 2],
    semantic: { type: 'computed', description: 'Doubled count' },
    ...overrides,
  };
}

function createActionFragment(overrides: Partial<ActionFragment> = {}): ActionFragment {
  return {
    id: 'action-1',
    kind: 'ActionFragment',
    requires: ['data.count'],
    provides: ['action:increment'],
    origin: { artifactId: 'test', location: { kind: 'generated', note: 'test' } },
    evidence: [],
    compilerVersion: '0.1.0',
    actionId: 'increment',
    effect: { _tag: 'SetValue', path: 'data.count' as any, value: 1 },
    semantic: { type: 'action', verb: 'increment', description: 'Increment count' },
    ...overrides,
  };
}

function createMinimalLinkResult(fragments: Fragment[]): LinkResult {
  return {
    fragments,
    conflicts: [],
    issues: [],
    version: 'test',
  };
}

function createMinimalDomainDraft(overrides: Partial<DomainDraft> = {}): DomainDraft {
  return {
    id: 'test-domain',
    name: 'Test Domain',
    description: 'A test domain',
    dataSchema: { count: 'number' },
    stateSchema: {},
    sources: {},
    derived: {},
    actions: {},
    initialState: {},
    ...overrides,
  };
}

// ============================================================================
// DomainDraft to ManifestoDomain Conversion Tests
// ============================================================================

describe('convertDomainDraftToManifesto', () => {
  describe('basic conversion', () => {
    it('should convert minimal DomainDraft', () => {
      const draft = createMinimalDomainDraft();

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.id).toBe('test-domain');
      expect(domain.name).toBe('Test Domain');
      expect(domain.description).toBe('A test domain');
      expect(domain.paths.sources).toEqual({});
      expect(domain.paths.derived).toEqual({});
      expect(domain.paths.async).toEqual({});
    });

    it('should use default values when id/name/description are missing', () => {
      const draft = createMinimalDomainDraft({
        id: undefined,
        name: undefined,
        description: undefined,
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.id).toBe('compiler-generated-domain');
      expect(domain.name).toBe('Generated Domain');
      expect(domain.description).toBe('Domain generated by @manifesto-ai/compiler');
    });

    it('should use custom defaults when provided', () => {
      const draft = createMinimalDomainDraft({
        id: undefined,
        name: undefined,
      });

      const domain = convertDomainDraftToManifesto(draft, {
        defaultId: 'custom-id',
        defaultName: 'Custom Name',
        defaultDescription: 'Custom description',
      });

      expect(domain.id).toBe('custom-id');
      expect(domain.name).toBe('Custom Name');
    });
  });

  describe('schema conversion', () => {
    it('should convert dataSchema to Zod schema', () => {
      const draft = createMinimalDomainDraft({
        dataSchema: {
          count: 'number',
          name: 'string',
          active: 'boolean',
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      // The dataSchema should be a Zod object
      expect(domain.dataSchema).toBeDefined();
      expect(typeof domain.dataSchema.parse).toBe('function');
    });

    it('should convert stateSchema to Zod schema', () => {
      const draft = createMinimalDomainDraft({
        stateSchema: {
          loading: 'boolean',
          error: 'string',
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.stateSchema).toBeDefined();
      expect(typeof domain.stateSchema.parse).toBe('function');
    });

    it('should handle optional types', () => {
      const draft = createMinimalDomainDraft({
        dataSchema: {
          optional: 'string?',
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      // Should parse successfully with undefined
      const result = domain.dataSchema.safeParse({ optional: undefined });
      expect(result.success).toBe(true);
    });

    it('should handle nullable types', () => {
      const draft = createMinimalDomainDraft({
        dataSchema: {
          nullable: 'string | null',
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      // Should parse successfully with null
      const result = domain.dataSchema.safeParse({ nullable: null });
      expect(result.success).toBe(true);
    });
  });

  describe('sources and derived', () => {
    it('should preserve source definitions', () => {
      const draft = createMinimalDomainDraft({
        sources: {
          'data.input': {
            schema: {} as any, // Will be a Zod schema in practice
            semantic: { type: 'input', description: 'Input field' },
          },
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.paths.sources['data.input']).toBeDefined();
      expect(domain.paths.sources['data.input'].semantic.type).toBe('input');
    });

    it('should preserve derived definitions', () => {
      const draft = createMinimalDomainDraft({
        derived: {
          'derived.total': {
            deps: ['data.a', 'data.b'],
            expr: ['+', ['get', 'data.a'], ['get', 'data.b']],
            semantic: { type: 'computed', description: 'Sum' },
          },
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.paths.derived['derived.total']).toBeDefined();
      expect(domain.paths.derived['derived.total'].deps).toEqual(['data.a', 'data.b']);
    });
  });

  describe('actions', () => {
    it('should preserve action definitions', () => {
      const draft = createMinimalDomainDraft({
        actions: {
          submit: {
            deps: ['data.form'],
            effect: { _tag: 'SetValue', path: 'state.submitted' as any, value: true },
            semantic: { type: 'action', description: 'Submit', verb: 'submit' },
          },
        },
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.actions.submit).toBeDefined();
      expect(domain.actions.submit.deps).toEqual(['data.form']);
    });
  });

  describe('initial state', () => {
    it('should use provided initialState', () => {
      const draft = createMinimalDomainDraft({
        stateSchema: { loading: 'boolean' },
        initialState: { loading: true },
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.initialState).toEqual({ loading: true });
    });

    it('should build default initialState from schema when not provided', () => {
      const draft = createMinimalDomainDraft({
        stateSchema: { loading: 'boolean', count: 'number' },
        initialState: undefined,
      });

      const domain = convertDomainDraftToManifesto(draft);

      expect(domain.initialState).toHaveProperty('loading');
      expect(domain.initialState).toHaveProperty('count');
    });
  });
});

// ============================================================================
// buildZodSchemaFromRecord Tests
// ============================================================================

describe('buildZodSchemaFromRecord', () => {
  it('should build schema for basic types', () => {
    const schema = buildZodSchemaFromRecord({
      str: 'string',
      num: 'number',
      bool: 'boolean',
    });

    const result = schema.safeParse({
      str: 'hello',
      num: 42,
      bool: true,
    });

    expect(result.success).toBe(true);
  });

  it('should handle array and object types', () => {
    const schema = buildZodSchemaFromRecord({
      arr: 'array',
      obj: 'object',
    });

    const result = schema.safeParse({
      arr: [1, 2, 3],
      obj: { key: 'value' },
    });

    expect(result.success).toBe(true);
  });

  it('should handle unknown types gracefully', () => {
    const schema = buildZodSchemaFromRecord({
      custom: 'CustomType',
    });

    // Unknown types become z.unknown()
    const result = schema.safeParse({
      custom: 'anything',
    });

    expect(result.success).toBe(true);
  });
});

// ============================================================================
// isDraftConvertible Tests
// ============================================================================

describe('isDraftConvertible', () => {
  it('should return valid for complete draft', () => {
    const draft = createMinimalDomainDraft();

    const result = isDraftConvertible(draft);

    expect(result.isValid).toBe(true);
    expect(result.issues).toHaveLength(0);
  });

  it('should report empty data schema', () => {
    const draft = createMinimalDomainDraft({
      dataSchema: {},
    });

    const result = isDraftConvertible(draft);

    expect(result.issues).toContain('Empty data schema');
  });
});

// ============================================================================
// Core Validation Integration Tests
// ============================================================================

describe('verify with useCoreValidation', () => {
  describe('when useCoreValidation=false (default)', () => {
    it('should not call Core validation', () => {
      const fragments: Fragment[] = [
        createSchemaFragment(),
        createDerivedFragment(),
      ];
      const linkResult = link(fragments);

      const result = verify(linkResult, { useCoreValidation: false });

      // Should pass without Core validation
      expect(result.isValid).toBe(true);
    });
  });

  describe('when useCoreValidation=true', () => {
    it('should pass for valid domain', () => {
      // Use only SourceFragment for paths (no SchemaFragment to avoid conflict)
      // SourceFragment provides the path AND creates the source definition
      const fragments: Fragment[] = [
        createSourceFragment({
          id: 'source-count',
          provides: ['data.count'],
          path: 'data.count',
          type: 'number',
          schema: { type: 'number' },
          semantic: { type: 'number', description: 'Count value' },
        }),
        createDerivedFragment({
          id: 'derived-doubled',
          provides: ['derived.doubled'],
          requires: ['data.count'],
        }),
      ];

      const linkResult = link(fragments, { buildDomain: true });

      // Ensure domain was built
      expect(linkResult.domain).toBeDefined();

      // Without Core validation first to establish baseline
      const baseResult = verify(linkResult, { useCoreValidation: false });

      // With Core validation
      const result = verify(linkResult, { useCoreValidation: true });

      // Debug: Log any issues
      if (!result.isValid) {
        console.log('Issues:', result.issues.map(i => `[${i.severity}] ${i.code}: ${i.message}`));
      }

      // Should pass Core validation
      expect(result.isValid).toBe(true);
    });

    it('should skip Core validation when no domain exists', () => {
      const linkResult: LinkResult = {
        fragments: [],
        conflicts: [],
        issues: [],
        version: 'test',
        domain: undefined,
      };

      const result = verify(linkResult, { useCoreValidation: true });

      // Should not fail when domain is missing
      expect(result.isValid).toBe(true);
    });

    it('should handle Core validation errors gracefully', () => {
      // Create a minimal link result with domain
      const linkResult: LinkResult = {
        fragments: [createSchemaFragment()],
        conflicts: [],
        issues: [],
        version: 'test',
        domain: createMinimalDomainDraft(),
      };

      // Core validation should run without throwing
      expect(() => verify(linkResult, { useCoreValidation: true })).not.toThrow();
    });
  });

  describe('determinism (Principle E)', () => {
    it('should produce consistent results with Core validation', () => {
      // Use only SourceFragments for paths (no SchemaFragment to avoid conflict)
      const fragments: Fragment[] = [
        createSourceFragment({
          id: 'source-a',
          provides: ['data.a'],
          path: 'data.a',
          type: 'number',
          schema: { type: 'number' },
          semantic: { type: 'number', description: 'Value A' },
        }),
        createSourceFragment({
          id: 'source-b',
          provides: ['data.b'],
          path: 'data.b',
          type: 'string',
          schema: { type: 'string' },
          semantic: { type: 'string', description: 'Value B' },
        }),
        createDerivedFragment({
          id: 'derived-x',
          provides: ['derived.x'],
          requires: ['data.a'],
        }),
      ];

      const linkResult = link(fragments, { buildDomain: true });

      const result1 = verify(linkResult, { useCoreValidation: true });
      const result2 = verify(linkResult, { useCoreValidation: true });

      expect(result1.isValid).toBe(result2.isValid);
      expect(result1.errorCount).toBe(result2.errorCount);
      expect(result1.warningCount).toBe(result2.warningCount);
      // Compare issue codes instead of IDs (IDs contain random components for uniqueness)
      expect(result1.issues.map((i) => i.code).sort()).toEqual(result2.issues.map((i) => i.code).sort());
    });
  });
});

// ============================================================================
// Integration with Full Pipeline
// ============================================================================

describe('full pipeline with Core validation', () => {
  it('should verify complete domain through linker and verifier', () => {
    // Use only SourceFragment for paths (no SchemaFragment to avoid conflict)
    const fragments: Fragment[] = [
      createSourceFragment({
        id: 'source-count',
        provides: ['data.count'],
        path: 'data.count',
        type: 'number',
        schema: { type: 'number' },
        semantic: { type: 'number', description: 'Count value' },
      }),
      createDerivedFragment({
        id: 'derived-doubled',
        provides: ['derived.doubled'],
        requires: ['data.count'],
        path: 'derived.doubled',
        expr: ['*', ['get', 'data.count'], 2],
      }),
      createActionFragment({
        id: 'action-increment',
        provides: ['action:increment'],
        requires: ['data.count'],
        actionId: 'increment',
        effect: { _tag: 'SetValue', path: 'data.count' as any, value: 1 },
      }),
    ];

    // Link fragments
    const linkResult = link(fragments, { buildDomain: true });

    expect(linkResult.domain).toBeDefined();
    expect(linkResult.conflicts).toHaveLength(0);

    // Verify with Core validation
    const verifyResult = verify(linkResult, { useCoreValidation: true });

    // Should pass all validations
    expect(verifyResult.isValid).toBe(true);
    expect(verifyResult.errorCount).toBe(0);
  });

  it('should detect issues in incomplete domain', () => {
    const fragments: Fragment[] = [
      createDerivedFragment({
        id: 'derived-x',
        provides: ['derived.x'],
        requires: ['data.missing'], // Missing dependency
        path: 'derived.x',
      }),
    ];

    const linkResult = link(fragments, { buildDomain: true });
    const verifyResult = verify(linkResult, { useCoreValidation: true });

    expect(verifyResult.isValid).toBe(false);
    expect(verifyResult.issues.some((i) => i.code === 'MISSING_DEPENDENCY')).toBe(true);
  });
});
